Ensure missing dependencies are installed via go get
Without `-u` flag when running a clean install, `github.com/golang/protobuf` is not installed:

```
$ go get github.com/micro/micro
# github.com/micro/micro/bot/proto
bot/proto/bot.pb.go:220: undefined: proto.RegisterFile
```